mysql:
    table: pp_players
    port: 3306
    username: root
    hostname: localhost
    password: ''
    database: minecraft
notifyPurchase: group.advisor
locale: enUS
autoLoadDefaultLocales: true
useBuyPermission: false