name: PurchasePermissions
main: com.cyprias.purchasepermissions.PurchasePermissions
version: 0.1.4

commands:
    pp:
      description: Test
      usage: /<command>
permissions:
    purchasepermissions.*:
        description: Gives access to all commands
        children:
            purchasepermissions.create: true
            purchasepermissions.modify: true
            purchasepermissions.remove: true
    purchasepermissions.create:
        description: Allows you to create a permission.
        default: op
    purchasepermissions.modify:
        description: Allows you to modify a permission.
        default: op
    purchasepermissions.remove:
        description: Allows you to remove a permission.
        default: op
    purchasepermissions.buy.*:
        description: Allows you to buy a permission.
        default: op